import Link from "next/link";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <p>현대카드 무이자이벤트중</p>
        {children}
      </body>
    </html>
  );
}
